<?php include_once("includes/basic_includes.php");?>
<?php include_once("functions.php"); ?>

<!DOCTYPE HTML>
<html>
<head>
<title>Find Your Perfect Partner - Makemylove
 | Terms :: Make My Love
</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="css/bootstrap-3.1.1.min.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<!-- Custom Theme files -->
<link href="css/style.css" rel='stylesheet' type='text/css' />
<link href='//fonts.googleapis.com/css?family=Oswald:300,400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
<!----font-Awesome----->
<link href="css/font-awesome.css" rel="stylesheet"> 
<!----font-Awesome----->
<script>
$(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});
</script>
</head>
<body>
<!-- ============================  Navigation Start =========================== -->
<?php include_once("includes/navigation.php");?>
<!-- ============================  Navigation End ============================ -->
<div class="grid_3">
  <div class="container">
   <div class="breadcrumb1">
     <ul>
        <a href="index.php"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">Terms and Conditions</li>
     </ul>
   </div>
   <div class="terms_1">
   <p>This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under pertaining to electronic records as applicable and amended. This electronic record is generated by a computer system and does not require any physical or digital signatures.

	This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and the terms and conditions for access or usage of Marital (the "Website").

	PLEASE READ THE FOLLOWING TERMS AND CONDITIONS VERY CAREFULLY BEFORE USING THE WEBSITE. ACCESSING, BROWSING OR OTHERWISE USING THE WEBSITE IMPLIES YOUR AGREEMENT TO BE BOUND BY ALL THESE TERMS AND CONDITIONS ("Agreement"). If you do not want to be bound by the Terms and Conditions, you must not use the Website or the Marital Services. The Terms and Conditions also includes the applicable policies which are incorporated herein by way of reference and as amended from time to time (the "Terms and conditions").</p>
	    <h5>1. Eligibility : </h5>   
	   <p>A) Marital and rights of admission is reserved solely for :

I. Indian Nationals & Citizens.

II. Persons of Indian Origin (PIO).

III. Non Resident Indians (NRI).

IV. Persons of Indian Descent or Indian Heritage

V. Persons who intend to marry persons of Indian Origin.

B) Further in capacity as BM member you confirm that you are :

I. 18 years or above (if you are a woman) or 21 years or above (if you are a man);

II. If you have applied for Divorce, you may register on our website/App by stating "Awaiting Divorce".

III. If you are a resident of any other Country, you are legally competent to marry as per the local rules applicable to your country and you shall comply with the Indian laws for marrying a person of Indian Origin

C) In case you are a Registrant of the prospective bride/ bridegroom and has created profile in M Website/App on behalf of them or is accessing the M Website/App on behalf of them implies that you have taken their consent for their profile creation in M and for accessing the M Website/App.</p>

<h5>2. Registration</h5>  
		<p>
A. We expect that you would complete the online registration process with fairness and honesty in furnishing true, accurate, current, complete information and with providing recent photos of you which will help you to meet your parameters .We expect you to read the relevant column before keying in the details or selecting the option available or uploading the photo. You are requested not to key in details of the profile in field other than the applicable field (including mentioning id's of other platforms/websites/App or repeating your details in another fields, after filling them once in the relevant fields or others photographs. In order to serve you better if M requires additional details you agree to provide it. You may also give a missed call to any of our retail outlets phone number for us to call you back and assist you in getting your profile registered on our website/App. Further you may fill in your email id and phone number in any of our registration campaigns appearing in various websites as part of our advertisements, basis which you may receive call from our Customer Service Center and assist you in getting your profile registered on our website/App. M may also reproduce your profile information in other matrimonial websites owned by MCL including community based websites to provide better matching Profiles to you.

B. If at any point of time M comes to know or is so informed by third party or has reasons to believe that any information provided by you for registration (including photos) or otherwise is found to be untrue, inaccurate, or incomplete,BM shall have full right to suspend or terminate (without any notice) your M membership and forfeit any amount paid by you towards M membership fee and refuse to provide M service to you thereafter.

C. M also reserves the right to block the registration of your profile on Website/App, if any, in the case of your contact details/links being entered in irrelevant fields or if there are errors in any data entered by the M members in their profile.

D. Registration of duplicate profiles of the same person is not allowed in M Website/App. M shall have full right to suspend or terminate (without any notice) such duplicate profile.

E. You acknowledge and confirm that your registration with M and the usage of M services is with the bonafide intention of marriage and not otherwise. M Membership is restricted strictly to the registered M individual member only. Organizations, companies, businesses and/or individuals carrying on similar or competitive business cannot become Members of M and nor use the M Service or M members data for any commercial purpose, and M reserves its right to initiate appropriate legal action for breach of these obligation.</p>
     </div>
   </div>
</div>


<?php include_once("footer.php");?>

</body>
</html>	